/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package views;

import controladores.DisenadorController;
import entidades.Disenador;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jferpon
 */
public class VistaDisenadores extends javax.swing.JDialog {

    /**
     * Creates new form VistaDisenadores
     */
    public VistaDisenadores(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cargarTablaDisenadores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setFont(new java.awt.Font("URW Bookman", 3, 14)); // NOI18N
        jButton1.setText("Añadir Diseñador");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 70, 340, 70));

        jButton2.setBackground(new java.awt.Color(0, 102, 102));
        jButton2.setFont(new java.awt.Font("URW Bookman", 3, 14)); // NOI18N
        jButton2.setText("Actualizar Diseñador");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 200, 340, 70));

        jButton3.setBackground(new java.awt.Color(0, 102, 102));
        jButton3.setFont(new java.awt.Font("URW Bookman", 3, 14)); // NOI18N
        jButton3.setText("Eliminar Diseñador");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 330, 340, 70));

        jButton4.setBackground(new java.awt.Color(0, 153, 153));
        jButton4.setFont(new java.awt.Font("URW Bookman", 3, 14)); // NOI18N
        jButton4.setText("Ver Perfumes");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 200, 60));

        jTable1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Apellido", "Fecha Nacimiento"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 530, -1));

        jLabel2.setFont(new java.awt.Font("URW Bookman", 3, 48)); // NOI18N
        jLabel2.setText("Diseñadores");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, 310, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/disenador.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 1580, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String nombre = JOptionPane.showInputDialog(this, "Introduce el nombre:");
            if (nombre == null || nombre.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Nombre obligatorio");
                return;
            }

            String ape1 = JOptionPane.showInputDialog(this, "Introduce el primer apellido:");
            if (ape1 == null || ape1.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Apellido obligatorio");
                return;
            }

            String fechaStr = JOptionPane.showInputDialog(this, "Introduce fecha nacimiento (dia/mes/año):");
            if (fechaStr == null || fechaStr.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Fecha obligatoria");
                return;
            }

            // Convertir String a java.util.Date con SimpleDateFormat
            java.text.SimpleDateFormat formatoFecha = new java.text.SimpleDateFormat("dd/MM/yyyy");
            java.util.Date fechaNacimiento;
            try {
                fechaNacimiento = formatoFecha.parse(fechaStr);
            } catch (java.text.ParseException e) {
                JOptionPane.showMessageDialog(this, "Formato de fecha inválido. Usa dia/mes/año");
                return;
            }

            Disenador nuevo = new Disenador();
            nuevo.setNombre(nombre);
            nuevo.setApe1(ape1);
            nuevo.setFecNacimiento(fechaNacimiento);

            DisenadorController controller = new DisenadorController();
            controller.create(nuevo);

            cargarTablaDisenadores();

            JOptionPane.showMessageDialog(this, "Diseñador añadido con éxito");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al añadir diseñador: " + ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         int filaSeleccionada = jTable1.getSelectedRow();
    if (filaSeleccionada == -1) {
        JOptionPane.showMessageDialog(this, "Por favor selecciona un diseñador de la tabla para eliminar");
        return;
    }

    int id = (int) jTable1.getValueAt(filaSeleccionada, 0);

    DisenadorController controller = new DisenadorController();
    Disenador d = controller.findById(id);
    if (d == null) {
        JOptionPane.showMessageDialog(this, "Diseñador no encontrado");
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(this,
            "¿Estás seguro de eliminar al diseñador: " + d.getNombre() + " " + d.getApe1() + "?",
            "Confirmar eliminación",
            JOptionPane.YES_NO_OPTION);

    if (confirm == JOptionPane.YES_OPTION) {
        controller.delete(id);
        cargarTablaDisenadores();
        JOptionPane.showMessageDialog(this, "Diseñador eliminado con éxito");
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

           int filaSeleccionada = jTable1.getSelectedRow();
    int columnaSeleccionada = jTable1.getSelectedColumn();

    if (filaSeleccionada == -1 || columnaSeleccionada == -1) {
        JOptionPane.showMessageDialog(this, "Selecciona una celda para actualizar.");
        return;
    }

    int id = (int) jTable1.getValueAt(filaSeleccionada, 0); // siempre la columna 0 es id

    DisenadorController controller = new DisenadorController();
    Disenador d = controller.findById(id);

    switch (columnaSeleccionada) {
        case 1: // Columna Nombre
            String nuevoNombre = JOptionPane.showInputDialog(this, "Nuevo Nombre:", d.getNombre());
            if (nuevoNombre == null) return;
            d.setNombre(nuevoNombre);
            break;

        case 2: // Columna Apellido
            String nuevoApe = JOptionPane.showInputDialog(this, "Nuevo Apellido:", d.getApe1());
            if (nuevoApe == null) return;
            d.setApe1(nuevoApe);
            break;

        case 3: // Columna Fecha Nacimiento
            java.text.SimpleDateFormat formatoFecha = new java.text.SimpleDateFormat("dd/MM/yyyy");
            String fechaActualStr = formatoFecha.format(d.getFecNacimiento());
            String nuevaFechaStr = JOptionPane.showInputDialog(this, "Nueva Fecha Nacimiento (dd/MM/yyyy):", fechaActualStr);
            if (nuevaFechaStr == null) return;
            try {
                d.setFecNacimiento(formatoFecha.parse(nuevaFechaStr));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Formato de fecha incorrecto.");
                return;
            }
            break;

        default:
            JOptionPane.showMessageDialog(this, "No puedes editar esta columna.");
            return;
    }

    controller.update(d);
    cargarTablaDisenadores();
    JOptionPane.showMessageDialog(this, "Diseñador actualizado");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       
    }//GEN-LAST:event_jButton4ActionPerformed

    private void cargarTablaDisenadores() {
        DisenadorController controller = new DisenadorController();
        List<Disenador> lista = controller.findAll();

        String[] columnas = {"Id", "Nombre", "Apellido", "Fecha Nacimiento"};
        DefaultTableModel modelo = new DefaultTableModel(columnas, 0) {
            public boolean CeldaEditable(int row, int column) {
                return false;
            }
        };

        // Formateador para la fecha
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");

        for (Disenador d : lista) {
            String fechaFormateada = d.getFecNacimiento() != null ? sdf.format(d.getFecNacimiento()) : "Sin fecha";
            Object[] fila = {
                d.getId(),
                d.getNombre(),
                d.getApe1(),
                fechaFormateada
            };
            modelo.addRow(fila);
        }

        jTable1.setModel(modelo);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaDisenadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaDisenadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaDisenadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaDisenadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VistaDisenadores dialog = new VistaDisenadores(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}